"""business settings and forecast engine

Revision ID: 9763603b7163
Revises: 523de1f79d30
Create Date: 2026-10-08 00:48:33.939029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9763603b7163'
down_revision: Union[str, Sequence[str], None] = '523de1f79d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('forecast_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('forecast_type', sa.String(length=20), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("forecast_type IN ('tender', 'job')", name='ck_forecast_versions_type'),
    sa.CheckConstraint("status IN ('draft', 'published', 'superseded', 'archived')", name='ck_forecast_versions_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'forecast_type', 'version_no', name='uq_forecast_versions_project_type_number')
    )
    op.create_index('ix_forecast_versions_project_type', 'forecast_versions', ['project_id', 'forecast_type'], unique=False)
    op.create_index('uq_forecast_versions_one_current', 'forecast_versions', ['project_id', 'forecast_type'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('forecast_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_version_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('headcount', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('employee_id IS NULL OR headcount = 1', name='ck_forecast_lines_named_headcount_one'),
    sa.CheckConstraint('headcount >= 1', name='ck_forecast_lines_headcount_min'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['forecast_version_id'], ['forecast_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_lines_version', 'forecast_lines', ['forecast_version_id'], unique=False)
    op.create_index('ix_forecast_lines_designation', 'forecast_lines', ['designation_id'], unique=False)
    op.create_index('ix_forecast_lines_employee', 'forecast_lines', ['employee_id'], unique=False)
    op.create_table('forecast_line_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_line_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('resolved_hourly_rate_snapshot', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('rate_source_snapshot', sa.String(length=20), nullable=True),
    sa.Column('rate_source_id_snapshot', sa.Integer(), nullable=True),
    sa.Column('currency_code_snapshot', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM month) = 1', name='ck_forecast_line_months_month_first_day'),
    sa.CheckConstraint('allocation_percentage >= 0 AND allocation_percentage <= 100', name='ck_forecast_line_months_allocation_range'),
    sa.ForeignKeyConstraint(['forecast_line_id'], ['forecast_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_line_id', 'month', name='uq_forecast_line_months_line_month')
    )
    # ### end Alembic commands ###

    # Business configuration (spec #22): 208-hour standard month, kept in
    # one place instead of being hard-coded across the application.
    business_settings = sa.table(
        'business_settings',
        sa.column('key', sa.String),
        sa.column('value', sa.String),
        sa.column('description', sa.String),
    )
    op.bulk_insert(
        business_settings,
        [
            {
                'key': 'monthly_standard_hours',
                'value': '208',
                'description': (
                    'Hours represented by a 100% allocation for one full month'
                ),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_line_months')
    op.drop_index('ix_forecast_lines_employee', table_name='forecast_lines')
    op.drop_index('ix_forecast_lines_designation', table_name='forecast_lines')
    op.drop_index('ix_forecast_lines_version', table_name='forecast_lines')
    op.drop_table('forecast_lines')
    op.drop_index('uq_forecast_versions_one_current', table_name='forecast_versions', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_forecast_versions_project_type', table_name='forecast_versions')
    op.drop_table('forecast_versions')
    op.drop_table('business_settings')
    # ### end Alembic commands ###
