from app.schemas.auth import CurrentUserResponse, LoginRequest
from app.schemas.role import (
    PermissionResponse,
    RoleCreate,
    RoleResponse,
    RoleUpdate,
)
from app.schemas.user import (
    UserCreate,
    UserListItem,
    UserPasswordReset,
    UserUpdate,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectDetail,
    ProjectListItem,
    ProjectUpdate,
    ProjectMembershipCreate,
    ProjectMembershipResponse,
    ProjectMembershipUpdate,
    ProjectApproverCreate,
    ProjectApproverResponse,
    ProjectApproverUpdate,
    _to_detail as _project_to_detail,
    _to_list_item as _project_to_list_item,
)
from app.schemas.reference import (
    DepartmentCreate,
    DepartmentResponse,
    DepartmentUpdate,
    DesignationCreate,
    DesignationResponse,
    DesignationUpdate,
    EmployeeCategoryCreate,
    EmployeeCategoryResponse,
    EmployeeCategoryUpdate,
    TradeCreate,
    TradeResponse,
    TradeUpdate,
    ResourceProviderCreate,
    ResourceProviderResponse,
    ResourceProviderUpdate,
)
from app.schemas.employee import (
    EmployeeCreate,
    EmployeeDetail,
    EmployeeListItem,
    EmployeeUpdate,
)
from app.schemas.forecast import (
    ForecastCloneRequest,
    ForecastLineCreate,
    ForecastLineResponse,
    ForecastLineSummary,
    ForecastLineUpdate,
    ForecastMonthCell,
    ForecastMonthCellInput,
    ForecastMonthsUpdate,
    ForecastVersionCreate,
    ForecastVersionDetail,
    ForecastVersionListItem,
    ForecastVersionUpdate,
)

__all__ = [
    "CurrentUserResponse",
    "LoginRequest",
    "PermissionResponse",
    "RoleCreate",
    "RoleResponse",
    "RoleUpdate",
    "UserCreate",
    "UserListItem",
    "UserPasswordReset",
    "UserUpdate",
    # projects / scope / approvers
    "ProjectCreate",
    "ProjectDetail",
    "ProjectListItem",
    "ProjectUpdate",
    "ProjectMembershipCreate",
    "ProjectMembershipResponse",
    "ProjectMembershipUpdate",
    "ProjectApproverCreate",
    "ProjectApproverResponse",
    "ProjectApproverUpdate",
    # reference data
    "DepartmentCreate",
    "DepartmentResponse",
    "DepartmentUpdate",
    "DesignationCreate",
    "DesignationResponse",
    "DesignationUpdate",
    "EmployeeCategoryCreate",
    "EmployeeCategoryResponse",
    "EmployeeCategoryUpdate",
    "TradeCreate",
    "TradeResponse",
    "TradeUpdate",
    "ResourceProviderCreate",
    "ResourceProviderResponse",
    "ResourceProviderUpdate",
    # employees
    "EmployeeCreate",
    "EmployeeDetail",
    "EmployeeListItem",
    "EmployeeUpdate",
    # forecasts
    "ForecastCloneRequest",
    "ForecastLineCreate",
    "ForecastLineResponse",
    "ForecastLineSummary",
    "ForecastLineUpdate",
    "ForecastMonthCell",
    "ForecastMonthCellInput",
    "ForecastMonthsUpdate",
    "ForecastVersionCreate",
    "ForecastVersionDetail",
    "ForecastVersionListItem",
    "ForecastVersionUpdate",
    # internal helpers (not for direct API use)
    "_project_to_detail",
    "_project_to_list_item",
]
